name: deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Set up Go 1.15
              uses: actions/setup-go@v1
              with:
                  go-version: 1.15
              id: go

            - name: Check out source code
              uses: actions/checkout@v1

            - name: Build
              run: |
                  go build -o build/TrendingBot src/*.go

            - name: deploy
              uses: garygrossgarten/github-action-scp@release
              with:
                  local: build
                  remote: ${{ secrets.REMOTE }}
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  atomicPut: true
